name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        type: [release, debug]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install doctest
        if: ${{ matrix.type == 'debug' }}
        run: |
          git clone https://github.com/doctest/doctest.git
          cd doctest
          mkdir out
          cd out
          cmake ..
          cmake --build .
          sudo cmake --install .

      - name: List presets
        run: cmake --list-presets=all .

      - name: Make preset
        run: cmake --preset linux-${{ matrix.type }}

      - name: Build
        run: cmake --build .
        working-directory: ./out/build/linux-${{ matrix.type }}

      - name: Test
        if: ${{ matrix.type == 'debug' }}
        run: ./IFCA_tests
        working-directory: ./out/build/linux-${{ matrix.type }}/tests/

  windows-x64:
    strategy:
      fail-fast: false
      matrix:
        type: [release, debug]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: List presets
        run: cmake --list-presets=all .

      - name: Build all
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          git clone https://github.com/doctest/doctest.git
          cd doctest
          mkdir out
          cd out
          cmake ..
          cmake --build .
          cmake --install .
          cd ../..
          cmake --preset x64-${{ matrix.type }}
          cd out/build/x64-${{ matrix.type }}
          cmake --build .

      - name: Test
        if: ${{ matrix.type == 'debug' }}
        run: .\IFCA_tests.exe
        working-directory: ./out/build/x64-${{ matrix.type }}/tests

  windows-x86:
    strategy:
      fail-fast: false
      matrix:
        type: [release, debug]
        os: [windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: List presets
        run: cmake --list-presets=all .

      - name: Build all
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          git clone https://github.com/doctest/doctest.git
          cd doctest
          mkdir out
          cd out
          cmake ..
          cmake --build .
          cmake --install .
          cd ../..
          cmake --preset x86-${{ matrix.type }}
          cd out/build/x86-${{ matrix.type }}
          cmake --build .

      - name: Test
        if: ${{ matrix.type == 'debug' }}
        run: .\IFCA_tests.exe
        working-directory: ./out/build/x86-${{ matrix.type }}/tests