name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        type: [release, debug]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

#      - name: Mark OS
#        run: echo "JOB_OS=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: List presets
        run: cmake --list-presets=all .

      - name: Make preset
        run: cmake --preset linux-${{ matrix.type }}

      - name: Build
        run: cmake --build .
        working-directory: ./out/build/linux-${{ matrix.type }}

# if debug run tests