name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    strategy:
      matrix:
        type: [release, debug]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Mark OS (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo "JOB_OS=linux" >> $GITHUB_ENV

      - name: Mark OS (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: echo "JOB_OS=windows" >> $GITHUB_ENV

      - name: Install doctest
        if: ${{ matrix.type == 'debug' }}
        run: |
          git clone https://github.com/doctest/doctest.git
          cd doctest
          mkdir out
          cd out
          cmake ..
          cmake --build .
          cmake --install .

      - name: List presets
        run: cmake --list-presets=all .

      - name: Make preset
        run: cmake --preset ${{ env.JOB_OS }}-${{ matrix.type }}

      - name: Build
        run: cmake --build .
        working-directory: ./out/build/${{ env.JOB_OS }}-${{ matrix.type }}

      - name: Test
        if: ${{ matrix.type == 'debug' }}
        run: ./IFCATest
        working-directory: ./out/build/${{ env.JOB_OS }}-${{ matrix.type }}/tests